//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.GravityFall {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.GravityFall.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball with number = {0} not found.
        /// </summary>
        internal static string ExceptionBallNotFound {
            get {
                return ResourceManager.GetString("ExceptionBallNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameboard contains no balls. Playing is impossible.
        /// </summary>
        internal static string ExceptionNoBalls {
            get {
                return ResourceManager.GetString("ExceptionNoBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameboard contains no holes. Playing is impossible.
        /// </summary>
        internal static string ExceptionNoHoles {
            get {
                return ResourceManager.GetString("ExceptionNoHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object&apos;s numbers are not unique.
        /// </summary>
        internal static string ExceptionObjectNumberDuplicate {
            get {
                return ResourceManager.GetString("ExceptionObjectNumberDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object&apos;s positions are not unique.
        /// </summary>
        internal static string ExceptionObjectPositionDuplicate {
            get {
                return ResourceManager.GetString("ExceptionObjectPositionDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object&apos;s position {0}, {1} is out of gameboard bounds {2}-{3}, {4}-{5}.
        /// </summary>
        internal static string ExceptionObjectPositionOutOfBoard {
            get {
                return ResourceManager.GetString("ExceptionObjectPositionOutOfBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string GravityBottom {
            get {
                return ResourceManager.GetString("GravityBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string GravityLeft {
            get {
                return ResourceManager.GetString("GravityLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string GravityRight {
            get {
                return ResourceManager.GetString("GravityRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string GravityTop {
            get {
                return ResourceManager.GetString("GravityTop", resourceCulture);
            }
        }
    }
}
